### ISSUE TITLE
Deletes do not sync to disconnected clients

### ISSUE THREAD

**Issue by wernst** [aspen-cloud/triplit#18]
Reproduction:
- Run a client with persistent storage, get it in sync with the server
- Take the client offline
- Perform a delete (remotely from the offline client)
- Take the client back online, the deletion does not sync to the client

**Comment by wernst** [comment]
Will be available in the next release

**Comment by MHOOO** [comment]
Is deletion still an issue?
I have a triplit sync server running and am trying to delete data from it:
* Client A deletes some data. Deletion is reflected on client A's view (i.e. a fetch yields none of the deleted entries)
* Client B does not get any updates (not even if this is the console.triplit.dev). This is weird, because even if I run the `clear()` method on the connected `TriplitClient`, the old data is still visible

**Comment by MHOOO** [comment]
To respond to my own question:
Yes, it appears deletion or even insertions are not synced, when offline. At least I am not able to get it to work, unless I explicity delete the browsers triplit database and have it fully sync again.

**Comment by wernst** [comment]
Hi it looks like we missed your original message around the holidays. Sorry about that! Is it possible to provide a recreation for us to look at?

Other helpful information would be the client and server versions you are using. 

I just set up some programmatic tests with the client and set one up in a browser app and saw correct syncing across connections and disconenctions. However it's certainly possible some state being incorrect could cause syncing issues.

**Comment by MHOOO** [comment]
I've already thought about how to reduce my program to a simpler variant that reproduces the issue, but have not had the time to do it yet.
Client version:
```
"@triplit/cli": "^0.6.35",
"@triplit/client": "^0.6.13",
"@triplit/db": "^0.5.20",
"@triplit/svelte": "^0.2.32",
```
Sync server version I'm not sure, since it uses the docker image with the `latest` tag. I remember last updating a few weeks ago, not sure how to determine the version though.
Is it possible that the sync server keeps the sync state per session / token? Because as it is now, I am only using two sessions / tokens to connect to the sync server. One from the backend and one from the frontend, even though the frontend is running on various browsers (both mobile and desktop). If the server kept some sort of state per token, then that would explain why some of the browsers do not sync properly.

On another note, what I have also noticed is that when I clear the database and then run a query with a limit, that limit effectively cuts of the amount of data that I will see. Even if I later remove the limit, I can only see the data that was requested with the first (limited) query. Only way to fix this is to then clear the database again and ensure that the first query does not have any limit set.
